# Generated by Django 4.1.1 on 2022-09-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_author_posts_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
